### PR TITLE
Adds IDNA support

### PR DESCRIPTION
**Pull request by jeremykendall**

### CODE REVIEW

**Comment by harikt** [comment]
@jeremykendall any idea why the test fails ?

**Comment by jeremykendall** [comment]
Working on it now.

**Comment by harikt** [comment]
Good to hear you have already noticed it.

As the PR is a big one, I will wait for @pmjones to merge.

Thanks!

**Comment by jeremykendall** [comment]
@harikt Fixed!

**Comment by pmjones** [comment]
I like it! But does adding the mbstring requirement count as a BC break?

**Comment by jeremykendall** [comment]
I don't _think_ so, as it's an extension and not an external API change. It's debatable, but I came down on the "no" side for PHP Domain Parser.

**Comment by jeremykendall** [comment]
FWIW, `intl` is also a new requirement, for the `idn_to_*` functions.

**Comment by harikt** [comment]
@pmjones may be you are thinking why not to 2.x branch .
This may be a reason we can release the 2.x version for Aura.Uri . So if they don't need they still can use? May be , may be not ;) . And also isn't the function `mb_parse_url` a compatibility if the extension is not installed ?

**Comment by harikt** [comment]
@jeremykendall intl is already bundled with php 5.3 . So no need of installing / configuring http://php.net/manual/en/intl.installation.php 

But the case of mbstring is not that .

**Comment by pmjones** [comment]
@jeremykendall I hate to say it but the consensus appears to favor my original intuition, that adding the mbstring requirement (and by implication the intl requirement) makes this a BC-breaking change. I think that means it's time to start on v2.

**Comment by pmjones** [comment]
Alternatively, if there is any way to avoid mbstring and intl, whether by writing the functions in userspace or some other way, that would avoid the BC-breaking change. But my guess is that's a lot of effort for little reward.

**Comment by harikt** [comment]
I agree with you Paul . If we merge this it will break, and I wonder whether there is a way that we do not force to install `ext-mbstring`. 

For eg : if I don't need the IDNA support I don't need mb-string . So I am wondering even if it is in v2 whether there is some way .

**Comment by jeremykendall** [comment]
> I hate to say it but the consensus appears to favor my original intuition, that adding the mbstring requirement (and by implication the intl requirement) makes this a BC-breaking change.

Understood.  I leaned towards "no" since the public API didn't change, but having to install a new extension can indicate a BC break.  No prob.

> Alternatively, if there is any way to avoid mbstring and intl, whether by writing the functions in userspace or some other way, that would avoid the BC-breaking change. But my guess is that's a lot of effort for little reward.

Yeah, that would be a long run for a short slide, IMHO.

> if I don't need the IDNA support I don't need mb-string.

You'll need `mbstring` regardless since [`mb_parse_url`](https://github.com/jeremykendall/Aura.Uri/blob/feature/idna-support/src/mb-parse-url.php) requires it.  Trying to programmatically determine whether `mb_parse_url` or `parse_url` should be used, depending on the URL to be parsed, would likely be extremely difficult and not worth the hassle.

**Comment by jeremykendall** [comment]
Correction: `mb_parse_url` doesn't require `mbstring`.  It's the [two](https://github.com/jeremykendall/Aura.Uri/blob/feature/idna-support/src/Aura/Uri/PublicSuffixList.php#L116) [instances](https://github.com/jeremykendall/Aura.Uri/blob/feature/idna-support/src/Aura/Uri/Url/Factory.php#L96) of `mb_strtolower` that require it.

**Comment by pmjones** [comment]
Agreed all around. I'm going to close this PR as a result, but we should begin planning the feature set on v2 based on this discussion. Also, as @harikt mentioned, this may be an opportunity to split some functionality into a separate package (or maybe not, depends on how closely everything has to collaborate).

**Comment by jeremykendall** [comment]
#26 should be closed as well, as it updates `mb_parse_url`.

**Comment by pmjones** [comment]
Gotcha -- I will do so.

**Pull request closed without merging**
