### PR TITLE
Adds IPv6 support

### PR DESCRIPTION
**Pull request by jeremykendall**
- Contains all commits from #25, because ...
- ... only relevant if https://github.com/auraphp/Aura.Uri/pull/25 is merged (I wanted to do the work now, as a reminder to myself)
- If https://github.com/auraphp/Aura.Uri/pull/25 is merged, the only additional change is https://github.com/jeremykendall/Aura.Uri/commit/0857cc23f1f0d0b751c762b33d8cd72cbef1bfa6
- If #25 is not merged, I'll need to review what's needed to add IPv6 support.
- Based on https://github.com/jeremykendall/php-domain-parser/pull/35

### CODE REVIEW

**Comment by harikt** [comment]
Does this PR also contains the commits of PR #25 ? So we only need to merge this.

**Comment by jeremykendall** [comment]
@harikt Yes.  I updated the PR description to make that clear.  I branched this PR off of https://github.com/jeremykendall/Aura.Uri/tree/feature/idna-support (the base for #25) because that's the only way this PR is relevant.  That is to say, without #25, I'll have to add IPv6 support in a different way.

**Comment by harikt** [comment]
/me nods. So we can close #25  in favour of #26 .

**Comment by jeremykendall** [comment]
@harikt I'd keep them both open to keep the feature additions separate.  There's a lot of work in #25 and it's all about IDNA domains, and a one line change in #26 to add IPv6 support.  Yes, it includes everything in #25, but only until #25 gets merged.  

Does that make sense?  Just my opinion.  I like keeping distinct features in their own PRs.

**Comment by harikt** [comment]
We will wait for @pmjones . I get what you mean. 

Just for clarity why I was confused is, you branch out from `develop`

```
git checkout -b feature/idna-support
// Your idna changes
git commit -m "Some message"
// Send this branch as PR 25
git checkout -b feature/ipv6-support
git commit -m "Some message"
// this is PR 26 
```

then I feel you don't need to merge `feature/idna-support` for all the changes are there in `feature/ipv6-support` .

And what I understood is there is only one commit that makes the `ipv6-support` if #25 and #26 don't get merged, then you may want to branch out from `develop` to another fresh branch and take the commit of `feature/ipv6-support` .

I don't want you to get stressed if I am wrong and no more comments from me :) .

**Comment by harikt** [comment]
After re reading again I understood more that when merged we can see the message what went . So you are right :+1:  . Sorry for the hassle.

**Comment by jeremykendall** [comment]
No worries!

**Comment by pmjones** [comment]
Per the discussion on #25, this represents a BC break. As such, I'm closing the PR in favor of starting discussions on a v2 package. Thanks @jeremykendall for your work here!

**Pull request closed without merging**
