### PR TITLE
Add public suffix list host/domain parsing

### PR DESCRIPTION
**Pull request by jeremykendall**
Here's the merge of php-domain-parser and Aura.Uri.  The good news is it passes all the test cases, and I _think_ most of it makes good sense.

Here are my immediate areas of concern:
- **Class Names and Locations**: I'm not sure how you guys feel about having the PublicSuffixList\* classes mixed in with the other top level Uri classes.  I'm not sure that makes sense, but I wasn't sure where else to put them so they went there.
- **HttpAdapter Interface and class**: I know that Aura.Http exists, but I also know it's important for each component to be independent. The adapter I've added here is nice and simple, but 1) it's not an Aura.Http adapter and 2) it's lifted from Will Durand's [Geocoder](https://github.com/willdurand/Geocoder) and as such we'd have to give him credit and include his MIT license.  
  - I don't have a problem with crediting Will, but I don't know if you want to have to do that in Aura. We'd have to come up with another solution if not.
  - We'd probably want to add ext-curl as a requirement in composer.json. Does that violate the no external dependency rule?
- **vfsStream dev dependency**: I've added vfsStream as an external dev dependency in composer.json.  This allows for mocking the file system during some tests.  Does that violate the no dependency rule?
- **/tests/bootstrap.php**: The tests bootstrap now relies on composer to autoload vfsStream
- **Composer vendor binary**: In order to allow end-user updating of the Public Suffix List, I've added a bin directory and have added that bin to the composer.json file.

I'm sure there are some other areas that we'll need to discuss, and some possible refactoring to do, before finally merging this.  I just wanted to raise the above points because they nagged at me during development.

### CODE REVIEW

**Comment by jeremykendall** [comment]
Ah, crap.  I didn't realize I'd mixed in some of @pmjones's commits.  Not sure how to fix that.

**Comment by harikt** [comment]
Hey @jeremykendall , 

Looking at the commits I guess the problem was you merged master to your branch. All the development stuffs happen in develop branch.

I am not a git master, but I feel what you can do in this case is 

checkout to a new branch from develop ( merging the remote ) and later checkout your commits and commit there.

I wrote something earlier http://auraphp.github.com/2012/07/13/contributing-to-aura-project/ .

But I know you know better than me. But I just thought of pointing what I think.

Thank you for taking your time. Also @pmjones may be having some-other way of helping you.

**Comment by jeremykendall** [comment]
Hey @harikt,

If I knew better than you, I wouldn't have made the rookie mistake of `git pull upstream/master`.  Doh!

Thanks for the additional info.  I'm going to try and un-pooch this now.

JK

**Comment by jeremykendall** [comment]
Dear God, I'm just making it worse.  [This resolution looked good](http://git-scm.com/2010/03/02/undoing-merges.html) until it didn't. @pmjones, any suggestions?

**Comment by jeremykendall** [comment]
I created another local branch and un-pooched my merge of master into my feature branch.  Closing this pull request so I can open another, clean pull request.

**Comment by harikt** [comment]
:)

**Pull request closed without merging**
